// Overlap-replace determinism for the Review Canvas box logic (task 11.2).
//
// ============================================================================
//  Property 5: Overlap determinism   (Validates: Requirements 8.11)
// ============================================================================
//
// Requirement 8.11 / web `addManualItem`: when a user draws a NEW box that
// overlaps an existing SAME-TYPE box with an intersection-over-union of at
// least 0.6, the canvas REPLACES that box (keeping its number) instead of
// creating a duplicate. Stacked DISTINCT boxes — a box of the other type, or a
// same-type box whose IoU is below 0.6 — do NOT merge; they become a new item.
//
// The decision primitive under test is the pure `findOverlappingItem`
// (backed by `segIoU`, `OVERLAP = 0.6`) ported verbatim in
// `lib/features/review/box_logic.dart`. The tiny "apply the decision" reducer
// (`_applyDraw` below) reproduces the documented web `addManualItem` flow —
// replace-in-place on a hit (count unchanged, number preserved) versus append
// on a miss (count + 1) — so the property exercises the exact behavior the
// requirement describes.
//
// HOW THIS REALIZES PROPERTY 5 (property-based testing note):
// There is no QuickCheck/Hypothesis-style package in this project's pubspec, so
// — as the rest of the suite does (see test/dto_roundtrip_test.dart) — the
// property is realized with a *seeded* pseudo-random generator
// (`math.Random(seed)`) that produces many randomized-but-valid box layouts per
// iteration. Determinism (fixed seeds) keeps any failure reproducible. The
// invariant must hold for every generated input, which is what makes this a
// property test rather than a handful of examples.

import 'dart:math' as math;

import 'package:flutter_test/flutter_test.dart';

import 'package:qpic_desktop/features/review/box_logic.dart';
import 'package:qpic_desktop/models/crop.dart';

/// Randomized cases generated per property. Large enough to span the IoU
/// threshold and varied layouts while keeping the suite fast.
const int _iterations = 400;

// ---------------------------------------------------------------------------
//  Test-local reducer: faithfully reproduces the web `addManualItem` flow,
//  using the box_logic decision primitives. Pure and deterministic.
// ---------------------------------------------------------------------------

typedef _DrawResult = ({
  List<AnalyzedItem> items, // resulting item list
  bool replaced, //          true => an existing item was replaced
  int matchedIndex, //       index that was replaced, or -1
});

/// Applies a freshly drawn box exactly as the web `addManualItem` does:
///  * if it overlaps a same-type item with IoU >= 0.6, replace that item in
///    place (segments := [seg], cleared flag, source := manual) and keep its
///    number unless the user typed one;
///  * otherwise append a new manual item, auto-numbered per type.
_DrawResult _applyDraw(
  List<AnalyzedItem> items,
  QuestionSegment seg,
  bool isSolution, {
  String? typedNum,
}) {
  final int idx = findOverlappingItem(seg, isSolution, items);
  final next = List<AnalyzedItem>.from(items);
  final bool typed = typedNum != null && typedNum.isNotEmpty;

  if (idx >= 0) {
    final AnalyzedItem hit = next[idx];
    next[idx] = AnalyzedItem(
      qNum: typed ? typedNum : hit.qNum, // number preserved unless retyped
      isSolution: hit.isSolution,
      segments: <QuestionSegment>[seg],
      source: 'manual',
      flagged: false,
      flagReason: null,
    );
    return (items: next, replaced: true, matchedIndex: idx);
  }

  next.add(AnalyzedItem(
    qNum: typed ? typedNum : nextAutoNumber(isSolution, items),
    isSolution: isSolution,
    segments: <QuestionSegment>[seg],
    source: 'manual',
    flagged: false,
    flagReason: null,
  ));
  return (items: next, replaced: false, matchedIndex: -1);
}

// ---------------------------------------------------------------------------
//  Helpers / generators (seeded)
// ---------------------------------------------------------------------------

QuestionSegment _seg(
  int page,
  double x0,
  double y0,
  double x1,
  double y1,
) =>
    QuestionSegment(
      page: page,
      xStartPct: x0,
      yStartPct: y0,
      xEndPct: x1,
      yEndPct: y1,
    );

AnalyzedItem _item(
  String qNum,
  bool isSolution,
  QuestionSegment seg, {
  bool flagged = false,
}) =>
    AnalyzedItem(
      qNum: qNum,
      isSolution: isSolution,
      segments: <QuestionSegment>[seg],
      source: 'auto',
      flagged: flagged,
    );

/// A box confined to the LEFT band (x in 5..40) of a page, so it is guaranteed
/// x-disjoint from any box generated by [_rightBox].
QuestionSegment _leftBox(math.Random r, int page) {
  final double x0 = 5.0 + r.nextInt(20); // 5..24
  final double w = 6.0 + r.nextInt(12); // width 6..17  -> x1 <= 41
  final double y0 = 5.0 + r.nextInt(60); // 5..64
  final double h = 8.0 + r.nextInt(25); // 8..32
  return _seg(page, x0, y0, x0 + w, math.min(100.0, y0 + h));
}

/// A LEFT-band box confined to vertical row [row] of [rows] equal rows, so a
/// list built one box per row is guaranteed mutually NON-overlapping (each has
/// IoU 0 with the others). This lets a redraw shrunk-inward on one row uniquely
/// overlap exactly that item — making `findOverlappingItem`'s first-match index
/// equal to the intended target.
QuestionSegment _leftRowBox(math.Random r, int page, int row, int rows) {
  // Each row owns a [rowTop, rowTop + rowH) slice with a small inner margin so
  // adjacent rows never touch.
  final double slice = 90.0 / rows; // usable page height 5..95
  final double rowTop = 5.0 + row * slice;
  final double margin = slice * 0.15;
  final double y0 = rowTop + margin + r.nextDouble() * (slice * 0.1);
  final double y1 = rowTop + slice - margin - r.nextDouble() * (slice * 0.1);
  final double x0 = 5.0 + r.nextInt(20); // 5..24
  final double w = 6.0 + r.nextInt(12); // width 6..17 -> x1 <= 41
  return _seg(page, x0, y0, x0 + w, y1);
}

/// A box confined to the RIGHT band (x in 60..95), guaranteed x-disjoint from
/// any [_leftBox] (IoU == 0 across the two bands).
QuestionSegment _rightBox(math.Random r, int page) {
  final double x0 = 60.0 + r.nextInt(20); // 60..79
  final double w = 6.0 + r.nextInt(12); // width 6..17 -> x1 <= 96
  final double y0 = 5.0 + r.nextInt(60);
  final double h = 8.0 + r.nextInt(25);
  return _seg(page, x0, y0, x0 + w, math.min(100.0, y0 + h));
}

/// A new box obtained by shrinking [b] inward by up to 8% of each dimension.
/// Because the result is strictly inside [b], the IoU equals areaNew/areaOld =
/// (1-2tx)(1-2ty) which, with tx,ty <= 0.08, is >= 0.84*0.84 = 0.70 >= 0.6.
QuestionSegment _shrinkInward(math.Random r, QuestionSegment b) {
  final double w = b.xEndPct - b.xStartPct;
  final double h = b.yEndPct - b.yStartPct;
  final double tx = r.nextDouble() * 0.08 * w;
  final double ty = r.nextDouble() * 0.08 * h;
  return _seg(
    b.page,
    b.xStartPct + tx,
    b.yStartPct + ty,
    b.xEndPct - tx,
    b.yEndPct - ty,
  );
}

// ---------------------------------------------------------------------------
//  Tests
// ---------------------------------------------------------------------------

void main() {
  // ========================================================================
  //  Unit tests — concrete examples and edge cases for the primitives.
  // ========================================================================
  group('segIoU (unit)', () {
    test('identical boxes have IoU 1.0', () {
      const a = QuestionSegment(
          page: 1, xStartPct: 10, yStartPct: 10, xEndPct: 40, yEndPct: 60);
      expect(segIoU(a, a), closeTo(1.0, 1e-9));
    });

    test('boxes on different pages never overlap', () {
      const a = QuestionSegment(
          page: 1, xStartPct: 10, yStartPct: 10, xEndPct: 40, yEndPct: 60);
      const b = QuestionSegment(
          page: 2, xStartPct: 10, yStartPct: 10, xEndPct: 40, yEndPct: 60);
      expect(segIoU(a, b), 0);
    });

    test('disjoint boxes have IoU 0', () {
      const a = QuestionSegment(
          page: 1, xStartPct: 10, yStartPct: 10, xEndPct: 30, yEndPct: 30);
      const b = QuestionSegment(
          page: 1, xStartPct: 60, yStartPct: 60, xEndPct: 80, yEndPct: 80);
      expect(segIoU(a, b), 0);
    });

    test('known half-area containment yields IoU 0.5', () {
      // a = 10x10 = 100 area; b is the left half of a (10x5 = 50), fully
      // contained -> inter 50, union 100 -> IoU 0.5.
      const a = QuestionSegment(
          page: 1, xStartPct: 0, yStartPct: 0, xEndPct: 10, yEndPct: 10);
      const b = QuestionSegment(
          page: 1, xStartPct: 0, yStartPct: 0, xEndPct: 5, yEndPct: 10);
      expect(segIoU(a, b), closeTo(0.5, 1e-9));
    });
  });

  group('findOverlappingItem (unit)', () {
    final existing = _item(
      '3',
      false,
      _seg(1, 10, 10, 40, 60),
    );

    test('same-type box with IoU >= 0.6 finds the item', () {
      // Shrunk-inward box: IoU ~0.81, same type -> match index 0.
      final draw = _seg(1, 12, 14, 38, 56);
      expect(segIoU(existing.segments.first, draw), greaterThanOrEqualTo(0.6));
      expect(findOverlappingItem(draw, false, <AnalyzedItem>[existing]), 0);
    });

    test('different-type box at the same place does NOT match', () {
      final draw = _seg(1, 10, 10, 40, 60); // identical region
      expect(
        findOverlappingItem(draw, true, <AnalyzedItem>[existing]),
        -1,
        reason: 'a solution drawn over a question must not merge',
      );
    });

    test('same-type box with IoU < 0.6 does NOT match', () {
      // Small box at a corner: tiny intersection -> IoU well below 0.6.
      final draw = _seg(1, 35, 55, 45, 65);
      expect(segIoU(existing.segments.first, draw), lessThan(0.6));
      expect(findOverlappingItem(draw, false, <AnalyzedItem>[existing]), -1);
    });
  });

  group('overlap-replace reducer (unit)', () {
    test('redrawing over an item replaces it: count unchanged, number kept',
        () {
      final items = <AnalyzedItem>[
        _item('3', false, _seg(1, 10, 10, 40, 60), flagged: true),
      ];
      final redraw = _seg(1, 12, 14, 38, 56); // IoU >= 0.6, same type
      final r = _applyDraw(items, redraw, false);

      expect(r.replaced, isTrue);
      expect(r.items.length, items.length, reason: 'no duplicate created');
      expect(r.items[0].qNum, '3', reason: 'existing number preserved');
      expect(r.items[0].segments.single, redraw);
      expect(r.items[0].flagged, isFalse, reason: 'flag cleared on re-select');
      expect(r.items[0].source, 'manual');
    });

    test('the classic "redrew Q3 -> still one Q3, not two" case', () {
      // Two questions; redraw over Q3. Count must stay 2; both numbers intact.
      final items = <AnalyzedItem>[
        _item('2', false, _seg(1, 10, 5, 45, 25)),
        _item('3', false, _seg(1, 10, 30, 45, 60)),
      ];
      final redraw = _seg(1, 12, 32, 43, 58); // overlaps Q3 only
      final r = _applyDraw(items, redraw, false);

      expect(r.items.length, 2);
      expect(r.matchedIndex, 1);
      expect(r.items.map((it) => it.qNum).toList(), <String>['2', '3']);
    });

    test('stacked distinct (different type) box does NOT merge', () {
      final items = <AnalyzedItem>[
        _item('1', false, _seg(1, 10, 10, 40, 60)),
      ];
      // Solution drawn on top of the identical region.
      final draw = _seg(1, 10, 10, 40, 60);
      final r = _applyDraw(items, draw, true);

      expect(r.replaced, isFalse);
      expect(r.items.length, 2, reason: 'distinct-type box is added, not merged');
      expect(r.items.last.isSolution, isTrue);
      expect(r.items.last.qNum, '1', reason: 'solutions number independently');
    });

    test('stacked same-type box below the 0.6 threshold does NOT merge', () {
      final items = <AnalyzedItem>[
        _item('1', false, _seg(1, 10, 10, 40, 60)),
      ];
      final draw = _seg(1, 35, 55, 45, 65); // IoU < 0.6
      final r = _applyDraw(items, draw, false);

      expect(r.replaced, isFalse);
      expect(r.items.length, 2);
      expect(r.items.last.qNum, '2', reason: 'auto-numbered max same-type + 1');
    });

    test('a typed number overrides the preserved number on replace', () {
      final items = <AnalyzedItem>[
        _item('3', false, _seg(1, 10, 10, 40, 60)),
      ];
      final redraw = _seg(1, 12, 14, 38, 56);
      final r = _applyDraw(items, redraw, false, typedNum: '9');

      expect(r.items.length, 1);
      expect(r.items[0].qNum, '9');
    });
  });

  // ========================================================================
  //  Property 5: Overlap determinism (seeded property generator)
  //  Validates: Requirements 8.11
  // ========================================================================
  group('Property 5 — overlap determinism', () {
    test('same-type IoU >= 0.6 redraw REPLACES (count unchanged, number kept)',
        () {
      for (var i = 0; i < _iterations; i++) {
        final r = math.Random(0x5a5a01 + i);
        final bool isSolution = r.nextBool();
        final int page = 1 + r.nextInt(3);

        // A list of same-type items placed in NON-overlapping vertical rows so
        // a redraw over one of them cannot accidentally overlap another item.
        final int count = 1 + r.nextInt(3);
        final items = <AnalyzedItem>[];
        for (var k = 0; k < count; k++) {
          items.add(_item('${k + 1}', isSolution, _leftRowBox(r, page, k, count)));
        }
        // Also drop in an opposite-type decoy at the same region to prove type
        // discrimination during replace.
        final int target = r.nextInt(count);
        items.add(_item('99', !isSolution, items[target].segments.first));

        final List<String> numsBefore =
            items.map((it) => it.qNum).toList(growable: false);

        // Redraw a same-type box that shrinks inward on the target -> IoU>=0.6.
        final QuestionSegment redraw =
            _shrinkInward(r, items[target].segments.first);
        expect(
          segIoU(items[target].segments.first, redraw),
          greaterThanOrEqualTo(0.6),
          reason: 'generator must produce an IoU >= 0.6 case (seed ${0x5a5a01 + i})',
        );

        final res = _applyDraw(items, redraw, isSolution);

        expect(res.replaced, isTrue,
            reason: 'IoU>=0.6 same-type must replace (seed ${0x5a5a01 + i})');
        expect(res.items.length, items.length,
            reason: 'count unchanged on replace (seed ${0x5a5a01 + i})');
        expect(res.matchedIndex, target,
            reason: 'the overlapped same-type item is the one replaced');
        // Every number is preserved (the replaced item keeps its own, the
        // others are untouched).
        expect(res.items.map((it) => it.qNum).toList(), numsBefore,
            reason: 'numbers preserved on replace (seed ${0x5a5a01 + i})');
        expect(res.items[target].segments.single, redraw);
      }
    });

    test('stacked DISTINCT boxes do not merge (different type or IoU < 0.6)',
        () {
      for (var i = 0; i < _iterations; i++) {
        final r = math.Random(0x7b7b02 + i);
        final bool isSolution = r.nextBool();
        final int page = 1 + r.nextInt(3);

        // Existing same-type items all live in the LEFT band.
        final int count = 1 + r.nextInt(3);
        final items = <AnalyzedItem>[];
        for (var k = 0; k < count; k++) {
          items.add(_item('${k + 1}', isSolution, _leftBox(r, page)));
        }

        if (r.nextBool()) {
          // Case A: same-type box in the RIGHT band -> IoU 0 with all items.
          final QuestionSegment draw = _rightBox(r, page);
          for (final it in items) {
            expect(segIoU(it.segments.first, draw), lessThan(0.6));
          }
          final res = _applyDraw(items, draw, isSolution);
          expect(res.replaced, isFalse,
              reason: 'non-overlapping same-type box must be added');
          expect(res.items.length, items.length + 1,
              reason: 'stacked-but-distinct does not merge (seed ${0x7b7b02 + i})');
          // Auto-number = max same-type + 1.
          expect(res.items.last.qNum, '${count + 1}');
        } else {
          // Case B: OPPOSITE-type box at the exact region of a left item
          // (IoU == 1.0) -> still must not merge because the type differs.
          final int target = r.nextInt(items.length);
          final QuestionSegment draw = items[target].segments.first;
          expect(segIoU(items[target].segments.first, draw), closeTo(1.0, 1e-9));
          final res = _applyDraw(items, draw, !isSolution);
          expect(res.replaced, isFalse,
              reason: 'different-type overlap must not merge (seed ${0x7b7b02 + i})');
          expect(res.items.length, items.length + 1);
          // First of the opposite type -> numbered 1.
          expect(res.items.last.qNum, '1');
          expect(res.items.last.isSolution, !isSolution);
        }
      }
    });

    test('the reducer is deterministic for identical inputs', () {
      for (var i = 0; i < _iterations; i++) {
        final r = math.Random(0x9c9c03 + i);
        final bool isSolution = r.nextBool();
        final int page = 1 + r.nextInt(3);
        final items = <AnalyzedItem>[
          _item('1', isSolution, _leftBox(r, page)),
          _item('2', isSolution, _leftBox(r, page)),
        ];
        // Either an overlapping redraw or a far box, chosen randomly.
        final QuestionSegment draw = r.nextBool()
            ? _shrinkInward(r, items[r.nextInt(items.length)].segments.first)
            : _rightBox(r, page);

        final a = _applyDraw(items, draw, isSolution);
        final b = _applyDraw(items, draw, isSolution);

        expect(a.replaced, b.replaced);
        expect(a.matchedIndex, b.matchedIndex);
        expect(a.items.length, b.items.length);
        for (var k = 0; k < a.items.length; k++) {
          expect(a.items[k].qNum, b.items[k].qNum);
          expect(a.items[k].isSolution, b.items[k].isSolution);
          expect(a.items[k].segments.single.xStartPct,
              b.items[k].segments.single.xStartPct);
          expect(a.items[k].segments.single.yEndPct,
              b.items[k].segments.single.yEndPct);
        }
      }
    });
  });
}
